### ISSUE TITLE
Tweak styles of 3 part date field / birthdate field to fit in better w/ docassemble style

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALToolbox#13]

**Comment by nonprofittechy** [comment]
The padding and size of the inputs is a little bit off when on the same screen as other inputs. Specifically, the text inputs look a little too large. It may be an illusion caused by the month/day/year label placement.

**Comment by BryceStevenWilley** [comment]
Still valid: From our perspective, it is a visual illusion (i.e. the text size is the same), but it still looks weird to us. We attempted to `text-align: left;` and then add the same amount of padding as options had, but neither looked great. Screen of what that looked like below.

![image](https://user-images.githubusercontent.com/6252212/184667018-848aaa8a-4498-429d-b7af-110ae779d5e8.png)

**Comment by plocket** [comment]
I believe neither of the two of the examples above were acceptable. Do we have other ideas? Should we close this?

**Comment by BryceStevenWilley** [comment]
I don't remember what it looks like now, but IMO the first example in the screen ahot is better.

I don't feel strongly about this, and I don't think it's come up from our partners (ILAO is very particular about looks, so if they haven't said anything I trust that). I'm in favor of closing.

**Comment by plocket** [comment]
Right now, it's all left aligned:

<img width="505" alt="date" src="https://github.com/SuffolkLITLab/docassemble-ALToolbox/assets/52798256/d8d48984-ff9f-491a-9a14-826283476584">

**Comment by BryceStevenWilley** [comment]
I checked what docassemble does when you put the label above inputs (like on small screens and with `label above field: True`), and it puts them flush to the left of the input, like we do currently.

![Screenshot from 2024-01-10 10-57-46](https://github.com/SuffolkLITLab/docassemble-ALToolbox/assets/6252212/4d6f27df-4059-4100-b6f9-a23e04491112)

There might be a better typographic choice here, but it's minor, and IMO there are other ways of improving the ThreePartDate that would be used instead of this. I'm gonna close this unless anyone objects (and has a better idea of what to do).
